### ISSUE TITLE
Vagrant Provison issue

### ISSUE THREAD

**Issue by MKBGOWDA** [chef/opscode-omnitruck#101]
Hi Team,

I'm trying to bring Vagrant up and found below error:
Details:
OS: Windows

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

sh install.sh -v 12.3.0 -d /tmp/vagrant-cache/vagrant_omnibus 2>&1

Stdout from the command:

Downloading Chef 12.3.0 for ubuntu...
downloading https://www.chef.io/chef/metadata?v=12.3.0&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
  to file /tmp/install.sh.1522/metadata.txt
trying wget...
trying perl...
trying python...
Unable to retrieve a valid package!
Version: 12.3.0

Please file a Bug Report at https://github.com/opscode/opscode-omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.getchef.com/support/tickets
More Chef support resources can be found at https://www.getchef.com/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

Metadata URL: https://www.chef.io/chef/metadata?v=12.3.0&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64

DEBUG OUTPUT FOLLOWS:

STDERR from wget:

--2015-05-11 10:16:36--  https://www.chef.io/chef/metadata?v=12.3.0&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
Resolving www.chef.io (www.chef.io)... 23.235.39.65
Connecting to www.chef.io (www.chef.io)|23.235.39.65|:443... connected.
ERROR: cannot verify www.chef.io's certificate, issued by ���/C=US/ST=MN/L=Minneapolis/O=Target Corporation/OU=Bluecoat/CN=Target Bluecoat SSL Intercept CA/emailAddress=stosupport@target.com���:
  Self-signed certificate encountered.
To connect to www.chef.io insecurely, use `--no-check-certificate'.

STDERR from perl:

Can't locate LWP/Simple.pm in @INC (you may need to install the LWP::Simple module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.

STDERR from python:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized

Thanks,
Mohan

**Comment by lamont-granquist** [comment]
somehow you've got an ubuntu 14.04 install where wget can't verify the certificate on https://www.chef.io/ 

either fix that or just connect to http://www.chef.io/chef/install.sh and bypass https
