### ISSUE TITLE
Unable to retrieve Chef Omnibus package!

### ISSUE THREAD

**Issue by rthomasson** [chef/opscode-omnitruck#104]
Encountering the following error while attempting to execute a kitchen converge that downloads and installs the Chef Omnibus package

STDERR from wget:\n\n--2015-06-02 15:53:30--  https://www.chef.io/chef/metadata?v=&prerelease=false&nightlies=false&p=el&pv=6&m=x86_64
      Resolving www.chef.io... failed: Name or service not known.
      wget: unable to resolve host address “www.chef.io”

**Comment by kevincox** [comment]
Sounds like your DNS is messed up.  Not chef's problem.
