### ISSUE TITLE
Error in knife bootstrap invocation

### ISSUE THREAD

**Issue by rajeshbijja** [chef/opscode-omnitruck#117]
Hi,
I am referring to the following Chef learning session on configuring a node using knife bootstrap
https://learn.chef.io/manage-a-node/rhel/bootstrap-your-node/
Used below command:
knife bootstrap nodehostname -x username -P 'password' '--sudo' --use-sudo-password -N node1 -r 'recipe[learn_chef_httpd]'
This is throwing the following error. I tried invoking the complete command as sudo <command> and the error is same in this case. Can you let me know what is the issue in this?
#############################################################################
Doing old-style registration with the validation key at file.pem...
Delete your validation key in order to use your user credentials instead

Connecting to nodehostname
nodehostname sudo: Please use single character options
nodehostname usage: sudo -V | -h | -L | -l | -v | -k | -K | [-H] [-P] [-S] [-b] [-p prompt]
nodehostname             [-u username/#uid] -s | <command>
#############################################################################

**Comment by rajeshkanna07** [comment]
This is on OEL 6 (x86_64)

**Comment by lamont-granquist** [comment]
issue doesn't have anything to do with omnitruck.  offhand, '--sudo' doesn't need those quotes around it.  -VV might give you more information about the sudo command it is trying to run.

possibly a dup of chef/chef#2887, `--use-sudo-password` may be buggy.
