### ISSUE TITLE
Problem in building vagrant box

### ISSUE THREAD

**Issue by deepak11627** [chef/opscode-omnitruck#118]
Getting the following error message in between the process,

==> default: urllib2.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>\n
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

sh install.sh -v 11.4.4 2>&1

Stdout from the command:

Downloading Chef 11.4.4 for el...
downloading https://www.getchef.com/chef/metadata?v=11.4.4&prerelease=false&nightlies=false&p=el&pv=6&m=x86_64
  to file /tmp/install.sh.7872/metadata.txt
trying wget...
trying curl...
grep: /tmp/install.sh.7872/stderr: No such file or directory
trying perl...
trying python...
Unable to retrieve a valid package!
Version: 11.4.4

Please file a Bug Report at https://github.com/opscode/opscode-omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.getchef.com/support/tickets
More Chef support resources can be found at https://www.getchef.com/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

Metadata URL: https://www.getchef.com/chef/metadata?v=11.4.4&prerelease=false&nightlies=false&p=el&pv=6&m=x86_64
\nDEBUG OUTPUT FOLLOWS:\n\nSTDERR from wget:\n\n--2015-08-13 05:49:39--  https://www.getchef.com/chef/metadata?v=11.4.4&prerelease=false&nightlies=false&p=el&pv=6&m=x86_64
Resolving www.getchef.com... failed: Temporary failure in name resolution.
wget: unable to resolve host address “www.getchef.com”\n\nSTDERR from perl:\n\nCan't locate LWP/Simple.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.\n\nSTDERR from python:\n\nTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 1198, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib64/python2.6/urllib2.py", line 1165, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>\n

Stderr from the command:

cp: cannot create regular file `/etc/chef/encrypted_data_bag_secret_key': No such file or directory

**Comment by lamont-granquist** [comment]
Your DNS is busted so 'www.getchef.com' isn't resolving, there's nothing really to fix on our end here.  You could try using the IP address directly to work around that.
