### ISSUE TITLE
Chef won't install on an Ubuntu Precise 32 machine

### ISSUE THREAD

**Issue by hotmeatballsoup** [chef/opscode-omnitruck#119]
I used Vagrant to spin up a new hashicorp/precise32 box. Then ran ‘vagrant up’ and ‘vagrant ssh’. From there I try installing Chef:

vagrant@precise32:~$ sudo curl -L https://www.opscode.com/chef/install.sh | bash 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18736  100 18736    0     0  38079      0 --:--:-- --:--:-- --:--:-- 91395
Downloading Chef  for ubuntu...
downloading https://www.opscode.com/chef/metadata?v=&prerelease=false&nightlies=false&p=ubuntu&pv=12.04&m=i686
  to file /tmp/install.sh.1437/metadata.txt
trying wget...
url	https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/10.04/i686/chef_12.4.1-1_i386.deb
md5	4c5b119c542a9a77a2a558aefd915b20
sha256	b2dfe413873d71d45cfc12536d4735443ce58cf2c550f195ace2434d441d3136
downloaded metadata file looks valid...
downloading https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/10.04/i686/chef_12.4.1-1_i386.deb
  to file /tmp/install.sh.1437/chef_12.4.1-1_i386.deb
trying wget...
Comparing checksum with sha256sum...

WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

You are installing an omnibus package without a version pin.  If you are installing
on production servers via an automated process this is DANGEROUS and you will
be upgraded without warning on new releases, even to new major releases.
Letting the version float is only appropriate in desktop, test, development or
CI/CD environments.

WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

Installing Chef 
installing with dpkg...
dpkg: error: requested operation requires superuser privilege
Installation failed
Version: 

Please file a Bug Report at https://github.com/opscode/opscode-omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.getchef.com/support/tickets
More Chef support resources can be found at https://www.getchef.com/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

Please advise.

**Comment by hotmeatballsoup** [comment]
Found the [solution here](http://docs.ansible.com/ansible/intro_getting_started.html) if anyone is interested. Goodbye Chef...

**Comment by jtimberman** [comment]
You used `sudo` for the `curl` command, not the `bash` command.

This part of the output you see is the key to determining the problem:

```
dpkg: error: requested operation requires superuser privilege
```

Switching to another tool is *not* the solution to this problem, but good luck.
