### ISSUE TITLE
www.chef.io does not yet have install.sh fix

### ISSUE THREAD

**Issue by L2G** [chef/opscode-omnitruck#75]
The script downloaded from https://www.chef.io/chef/install.sh does not contain the fix applied in 52959ff2858cd17e634a45dcddd8e4637aceb2d4.

If the script is run with certain Bourne shells, it can fail with a syntax error (unless this fix has been applied).

Specifically, the default shell in Solaris 11 (/usr/bin/sh) is known to fail:

```
vagrant@vagrant-solaris-11:~$ sh install.sh
install.sh: line 87: syntax error at line 172: ` ' unexpected
```

**Comment by lamont-granquist** [comment]
this got deployed awhile ago
