### ISSUE TITLE
Unable to setup a box using kitchen

### ISSUE THREAD

**Issue by kongakong** [chef/opscode-omnitruck#78]
I am following the instructions in chapter 6 in the book 'Learning chef'

Here is the error message.

$ kitchen setup default-centos65
-----> Starting Kitchen (v1.3.1)
-----> Converging <default-centos65>...
       Preparing files for transfer
       Preparing dna.json
       Berksfile, Cheffile, cookbooks/, or metadata.rb not found so Chef will run with effectively no cookbooks. Is this intended?
       Removing non-cookbook files before transfer
       Preparing solo.rb
-----> Installing Chef Omnibus (install only if missing)
       downloading https://www.chef.io/chef/install.sh
         to file /tmp/install.sh
       trying wget...
       Downloading Chef  for el...
       downloading https://www.chef.io/chef/metadata?v=&prerelease=false&nightlies=false&p=el&pv=6&m=x86_64
         to file /tmp/install.sh.2284/metadata.txt
       trying wget...
       trying curl...
       grep: /tmp/install.sh.2284/stderr: No such file or directory
       trying python...
       Unable to retrieve a valid package!
       Version:

       Please file a Bug Report at https://github.com/opscode/opscode-omnitruck/issues/new
       Alternatively, feel free to open a Support Ticket at https://www.getchef.com/support/tickets
       More Chef support resources can be found at https://www.getchef.com/support

       Please include as many details about the problem as possible i.e., how to reproduce
       the problem (if possible), type of the Operating System and its version, etc.,
       and any other relevant details that might help us with troubleshooting.

       Metadata URL: https://www.chef.io/chef/metadata?v=&prerelease=false&nightlies=false&p=el&pv=6&m=x86_64
       \nDEBUG OUTPUT FOLLOWS:\n\nSTDERR from wget:\n\n--2015-02-01 05:32:35--  https://www.chef.io/chef/metadata?v=&prerelease=false&nightlies=false&p=el&pv=6&m=x86_64
       Resolving www.chef.io... failed: Name or service not known.
       wget: unable to resolve host address “www.chef.io”\n\nSTDERR from python:\n\nTraceback (most recent call last):
         File "<string>", line 1, in <module>
         File "/usr/lib64/python2.6/urllib2.py", line 126, in urlopen
           return _opener.open(url, data, timeout)
         File "/usr/lib64/python2.6/urllib2.py", line 391, in open
           response = self._open(req, data)
         File "/usr/lib64/python2.6/urllib2.py", line 409, in _open
           '_open', req)
         File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
           result = func(*args)
         File "/usr/lib64/python2.6/urllib2.py", line 1198, in https_open
           return self.do_open(httplib.HTTPSConnection, req)
         File "/usr/lib64/python2.6/urllib2.py", line 1165, in do_open
           raise URLError(err)
       urllib2.URLError: <urlopen error [Errno -2] Name or service not known>\n

**Comment by kongakong** [comment]
If I login to the box, I am able to resolve the address www.chef.io

$ kitchen login default-centos65
Last login: Sun Feb  1 05:32:28 2015 from 10.0.2.2
Welcome to your Packer-built virtual machine.
[vagrant@default-centos65 ~]$ ping www.chef.io
PING chef.io (184.106.28.83) 56(84) bytes of data.
64 bytes from 184.106.28.83: icmp_seq=1 ttl=63 time=541 ms
64 bytes from 184.106.28.83: icmp_seq=2 ttl=63 time=239 ms
64 bytes from 184.106.28.83: icmp_seq=3 ttl=63 time=534 ms
64 bytes from 184.106.28.83: icmp_seq=4 ttl=63 time=288 ms

**Comment by lamont-granquist** [comment]
I don't have any ideas on that bug.  The output is very clear that its failing when wget does a dns lookup of www.chef.io.  Either there's a difference in what wget is doing vs. what ping is doing, or it fails early for some reason and then maybe gets a DHCP update later so it succeeds by the time you login.

**Comment by lamont-granquist** [comment]
Closing as unable to replicate

**Comment by spuder** [comment]
Did you resolve this? Test kitchen VM's that worked yesterday, are failing today. 



```
       Vagrant instance <default-ubuntu-1404> created.
       Finished creating <default-ubuntu-1404> (0m34.76s).
-----> Converging <default-ubuntu-1404>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.0.1...
       Removing non-cookbook files before transfer
       Preparing solo.rb
-----> Installing Chef Omnibus (install only if missing)
       Downloading https://www.chef.io/chef/install.sh to file /tmp/install.sh
       Trying wget...
       Trying python...
       Trying perl...
       Unable to download https://www.chef.io/chef/install.sh to /tmp/install.sh, aborting

       DEBUG OUTPUT FOLLOWS:

       STDERR from wget:

       --2015-12-10 21:40:48--  https://www.chef.io/chef/install.sh
       Resolving www.chef.io (www.chef.io)... failed: Name or service not known.
       wget: unable to resolve host address ‘www.chef.io’
```

When I try and resolve chef.io from my workstation it gives an ssl error

```
wget https://chef.io/chef/install.sh
--2015-12-10 14:47:59--  https://chef.io/chef/install.sh
Resolving chef.io... 184.106.28.82
Connecting to chef.io|184.106.28.82|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.chef.io/chef/install.sh [following]
--2015-12-10 14:47:59--  https://www.chef.io/chef/install.sh
Resolving www.chef.io... 23.235.40.65
Connecting to www.chef.io|23.235.40.65|:443... connected.
ERROR: cannot verify www.chef.io's certificate, issued by 'CN=GlobalSign Organization Validation CA - SHA256 - G2,O=GlobalSign nv-sa,C=BE':
  Issued certificate has expired.
To connect to www.chef.io insecurely, use `--no-check-certificate'.
```

**Comment by andreamaruccia** [comment]
ipconfig /flushdns for windows 8.1
