### ISSUE TITLE
Unable to retrieve a valid package!

### ISSUE THREAD

**Issue by mush20** [chef/opscode-omnitruck#84]
Downloading Chef  for ubuntu...
downloading https://www.chef.io/chef/metadata?v=&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
  to file /tmp/install.sh.1293/metadata.txt
trying wget...
url	https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/13.04/x86_64/chef_12.1.1-1_amd64.deb
md5	028e2335ff309fa4555ed0dfd486162f
sha256	108bc8a1786b1a4cfbb42dcea0e4990221340aae669878df3f67fffe1fb1ad24
downloaded metadata file looks valid...
downloading https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/13.04/x86_64/chef_12.1.1-1_amd64.deb
  to file /tmp/install.sh.1293/chef_12.1.1-1_amd64.deb
trying wget...
trying curl...
trying perl...
trying python...
Unable to retrieve a valid package!

**Comment by majoraze** [comment]
Same here!
You solved the problem?
Thanks!

**Comment by lamont-granquist** [comment]
The url works and there's no diagnostic output to determine what the problem was.  Reopen if its still an issue and you can give more details.
