### ISSUE TITLE
Chef Installation error

### ISSUE THREAD

**Issue by aswin3410** [chef/opscode-omnitruck#87]
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18378  100 18378    0     0   1544      0  0:00:11  0:00:11 --:--:--  5440
Downloading Chef  for ubuntu...
downloading https://www.opscode.com/chef/metadata?v=&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=i686
  to file /tmp/install.sh.8458/metadata.txt
trying wget...
url	https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/13.04/i686/chef_12.2.1-1_i386.deb
md5	e79d872e189d82a982f531018fd32263
sha256	c5948a5d4526d46a6def43f377d9f936838338bee6b58ad3b1f1f7c6826b4867
downloaded metadata file looks valid...
downloading https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/13.04/i686/chef_12.2.1-1_i386.deb
  to file /tmp/install.sh.8458/chef_12.2.1-1_i386.deb
trying wget...
Comparing checksum with sha256sum...
Installing Chef 
installing with dpkg...
dpkg: error: requested operation requires superuser privilege
Installation failed
Version: 

Please file a Bug Report at https://github.com/opscode/opscode-omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.getchef.com/support/tickets
More Chef support resources can be found at https://www.getchef.com/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

**Comment by lamont-granquist** [comment]
You have to run as root to install chef:

```
curl -L http://www.chef.io/chef/install.sh | sudo bash -s
```
